# Use root/example as user/password credentials
version: '3.1'

services:
  mqtt-broker:
    build: ./mosquitto/image
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./app:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - mqtt-broker
  nodered:
    build: ./nodered/image
    ports:
      - "1880:1880"
    volumes:
      - nodered-data:/data
    depends_on:
      - mqtt-broker
volumes:
  mosquitto-data:
    driver: local
  mosquitto-log:
    driver: local
  nodered-data:
    driver: local
